version: '3.8'

services:
  migrate:
    build:
      context: ./docker/migrate
      dockerfile: Dockerfile
      args:
        - POSTGRES_DRIVER_VERSION=${POSTGRES_DRIVER_VERSION}
    container_name: migrate
    hostname: migrate
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ="Asia/Tokyo"
    volumes:
      - type: bind
        source: ./sql
        target: /work/sql
      - ./html:/work/html
    depends_on:
      - db
    tty: true

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ="Asia/Tokyo"

  web:
    image: nginx:latest
    container_name: web
    hostname: web
    ports:
      - 10080:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
